# DataSource configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/myapp_db
spring.datasource.username=myapp_user
spring.datasource.password=myapp_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SQL init configuration
spring.sql.init.mode=always

# ============================= Druid ===================================
spring.datasource.druid.initial-size=5
spring.datasource.druid.min-idle=5
spring.datasource.druid.max-active=20
spring.datasource.druid.max-wait=60000
#spring.datasource.druid.validation-query=SELECT 1
# ??????????
spring.datasource.druid.stat-view-servlet.enabled=true
spring.datasource.druid.stat-view-servlet.url-pattern=/druid/*
spring.datasource.druid.stat-view-servlet.allow=127.0.0.1,172.0.0.0/8,10.0.0.0/8
spring.datasource.druid.stat-view-servlet.deny=
spring.datasource.druid.stat-view-servlet.login-username=admin
spring.datasource.druid.stat-view-servlet.login-password=admin
spring.datasource.druid.filters=stat,slf4j,config

spring.datasource.druid.filter.stat.enabled=true
spring.datasource.druid.filter.stat.db-type=postgresql
spring.datasource.druid.filter.stat.log-slow-sql=true
spring.datasource.druid.filter.stat.slow-sql-millis=100   
spring.datasource.druid.filter.stat.slow-sql-log-level=ERROR
spring.datasource.druid.filter.stat.merge-sql=true
spring.datasource.druid.filter.stat.merge-sql.cache=true

# ???????? ???
spring.datasource.druid.filter.stat.connection-connect-after-method=true
spring.datasource.druid.filter.stat.connection-connect-before-method=true
spring.datasource.druid.filter.stat.statement-create-after-method=true
spring.datasource.druid.filter.stat.statement-close-after-method=true
spring.datasource.druid.filter.stat.result-set-open-after-method=true
spring.datasource.druid.filter.stat.result-set-close-after-method=true


spring.datasource.druid.stat-view-servlet.reset-enable=true

spring.datasource.druid.web-stat-filter.enabled=true
spring.datasource.druid.web-stat-filter.url-pattern=/*
spring.datasource.druid.web-stat-filter.exclusions=
spring.datasource.druid.web-stat-filter.session-stat-enable=true
spring.datasource.druid.web-stat-filter.session-stat-max-count=10000
spring.datasource.druid.web-stat-filter.principal-session-name=user
spring.datasource.druid.web-stat-filter.principal-cookie-name=user
spring.datasource.druid.web-stat-filter.profile-enable=true



#============================L2 cache===========================================
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true

spring.jpa.properties.hibernate.cache.region.factory_class=infinispan

spring.jpa.properties.jakarta.persistence.sharedCache.mode=ALL
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.session.events.log=false
spring.jpa.properties.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=0



spring.jpa.properties.hibernate.cache.infinispan.query.expiration.lifespan=30000
spring.jpa.properties.hibernate.cache.infinispan.query.expiration.max_idle=30000
spring.jpa.properties.hibernate.cache.infinispan.quety.expiration.wake_up_interval=30000

#============================MInio=================================================================
minio.endpoint=http://minio:9000
minio.access-key=minioadmin
minio.secret-key=password
minio.bucket-name=import-files
minio.secure=false
# ??? ??????? ?????????? ??????????? SQL
logging.level.org.hibernate.SQL=OFF

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF


# ??? ????? ????????? ????? SQL ????? Hibernate
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.show-sql=false
#logging.level.org.hibernate.cache=DEBUG
#logging.level.org.infinispan=INFO
#logging.level.org.hibernate.stat=DEBUG